#+TITLE: Quotes on Mathematics and Computer Science

** [[https://es.wikipedia.org/wiki/Alan_Turing][Alan Turing]]

+ Codes are a puzzle. A game, just like any other game.
  + Los programas son rompecabezas. Un juego, como cualquier otro juego.

** [[https://en.wikipedia.org/wiki/Donald_Knuth][Donald Knuth]]

+ Computer programming is an art, because it applies accumulated knowledge to
  the world, because it requires skill and ingenuity, and especially because it
  produces objects of beauty. A programmer who subconsciously views himself as
  an artist will enjoy what he does and will do it better.
  + La programación de computadoras es un arte, porque aplica el conocimiento
    acumulado al mundo, porque requiere habilidad e ingenio, y especialmente
    porque produce objetos de belleza. Un programador que subconscientemente se ve
    a sí mismo como un artista disfrutará lo que hace y lo hará mejor.

+ Let us change our traditional attitude to the construction of programs:
  Instead of imagining that our main task is to instruct a computer what to do,
  let us concentrate rather on explaining to human beings what we want a
  computer to do.
  + Cambiemos nuestra actitud tradicional ante la construcción de programas: En
    lugar de imaginar que nuestra principal tarea es instruir a un ordenador
    sobre lo que debe hacer, concentrémonos más bien en explicar a los seres
    humanos lo que queremos que haga un ordenador.

** [[https://en.wikipedia.org/wiki/Edsger_W._Dijkstra][Edsger W. Dijkstra]]

+ Progress is possible only if we train ourselves to think about programs
  without thinking of them as pieces of executable code.
  + El progreso solo es posible si nos entrenamos para pensar en programas sin
    pensar en ellos como piezas de código ejecutable

** [[https://en.wikipedia.org/wiki/Georg_Gottlob][Georg Gottlob]]

+ Computer Science is the continuation of Logic by other means.
  + La ciencia de la computación es la continuación de la lógica por otros
    medios.

** [[https://en.wikipedia.org/wiki/Hal_Abelson][Harold Abelson]]

+ Programs must be written for people to read, and only incidentally for
  machines to execute.
  + Los programas deben estar escritos para que la gente los lea y, sólo de
    manera incidental, para que las máquinas los ejecuten.

** [[https://en.wikipedia.org/wiki/Martin_Fowler_(software_engineer)][Martin Fowler]]

+ Any fool can write code that a computer can understand. Good programmers
  write code that humans can understand.
  + Cualquier tonto puede escribir un código que un ordenador puede
    entender. Los buenos programadores escriben código que los humanos pueden
    entender.

** [[https://bit.ly/2JntZz3][Marvin Minsky]]

+ Computer languages of the future will be more concerned with goals and less
  with procedures specified by the programmer.
  + Los lenguajes informáticos del futuro estarán más preocupados por los
    objetivos y menos por los procedimientos especificados por el programador.

** [[https://es.wikipedia.org/wiki/Richard_Courant][Richard Courant]] y [[https://en.wikipedia.org/wiki/Herbert_Robbins][Herbert Robbins]]

+ Mathematics as an expression of the human mind reflects the active will, the
  contemplative reason, and the desire for aesthetic perfection. Its basic
  elements are logic and intuition, analysis and construction, generality and
  individuality.
  + Las matemáticas como expresión de la mente humana reflejan la voluntad
    activa, la razón contemplativa y el deseo de perfección estética. Sus
    elementos básicos son la lógica y la intuición, el análisis y la
    construcción, la generalidad y la individualidad.
